import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { readFileSync } from 'node:fs';
const FX=new URL('./fixtures/', import.meta.url).pathname;
const b64=p=>readFileSync(FX+p).toString('base64');
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1200,height:900}});
const errs=[];page.on('pageerror',e=>errs.push(e.message));page.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
let dl=null;page.on('download',async d=>{dl=await d.path();});
await page.goto(new URL('../index.html', import.meta.url).href);
let pass=0,fail=0;const ok=(n,c,d)=>{if(c){pass++;console.log('  OK',n);}else{fail++;console.log('  FAIL',n,'|',d);}};
await page.click('#railClean');
ok('레일 클릭 -> viewClean', await page.evaluate(()=>!document.getElementById('viewClean').classList.contains('hidden')), '');
ok('레일 4개', (await page.$$eval('.rail-btn',e=>e.length))===4, '');
ok('정보 아이콘 존재', await page.evaluate(()=>!!document.querySelector('#cleanSpecialInfo .info-icon')), '');
await page.evaluate(({a,b,x})=>{
  const mk=(s,n)=>{const bin=atob(s);const arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new File([arr],n);};
  window.__clean.addFiles([mk(a,'dirty_utf8.csv'), mk(b,'korean_cp949.csv'), mk(x,'messy.xlsx')]);
},{a:b64('dirty_utf8.csv'),b:b64('korean_cp949.csv'),x:b64('messy.xlsx')});
await page.waitForTimeout(100);
ok('파일 3개 목록', (await page.$$eval('.clean-file',e=>e.length))===3, '');
ok('변환 시작 활성', !(await page.$eval('#btnCleanRun',e=>e.disabled)), '');
await page.check('input[name=convMode][value=csv2csv]');
await page.waitForTimeout(50);
await page.click('#btnCleanRun');
await page.waitForFunction(()=>/완료/.test(document.getElementById('cleanStatus').textContent),{timeout:15000});
const statuses=await page.$$eval('.clean-file .cf-status',els=>els.map(e=>e.className.replace('cf-status ','')));
ok('csv 2개 성공', statuses.filter(s=>s.startsWith('ok')).length===2, JSON.stringify(statuses));
ok('xlsx 1개 실패(형식불일치)', statuses.filter(s=>s.startsWith('err')).length===1, JSON.stringify(statuses));
ok('결과 패널 표시', !(await page.evaluate(()=>document.getElementById('cleanResultPanel').classList.contains('hidden'))), '');
ok('요약 카드', await page.evaluate(()=>document.getElementById('cleanSummary').textContent.includes('정제·변환 요약')), '');
ok('진행률 100%', (await page.$eval('#cleanProgress',e=>parseFloat(e.style.width)||0))>=100, '');
ok('다운로드 힌트 ZIP', (await page.textContent('#cleanDownHint')).includes('ZIP'), await page.textContent('#cleanDownHint'));
await page.click('#btnCleanDownload');
await page.waitForTimeout(400);
ok('ZIP 다운로드', dl && dl.length>0, String(dl));
await page.screenshot({path:'/tmp/clean_ui.png', clip:{x:0,y:0,width:1200,height:760}});
console.log('\n결과: '+pass+' passed / '+fail+' failed');
console.log('page errors:', errs.length?errs:'none');
await browser.close();process.exit(fail?1:0);
