import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const browser = await chromium.launch();
const page = await browser.newPage();
const errs=[]; page.on('pageerror',e=>errs.push(e.message));
await page.goto(new URL('../index.html', import.meta.url).href);
let pass=0,fail=0; const ok=(n,c,d)=>{if(c){pass++;console.log('  OK',n);}else{fail++;console.log('  FAIL',n,'|',d);}};
const clean = (str, opts) => page.evaluate(({str,opts})=>{ const D=window.__anomaly.DataCleaner; const o=Object.assign({}, D.DEFAULTS, opts||{}); const ctx=D.makeContext(); return {out:D.cleanString(str,o,ctx), ctx}; },{str,opts});
const CTRL=String.fromCharCode(97,1,98);
const INV='a'+String.fromCharCode(0x200B,0xFEFF)+'b';
const EMO='안녕'+String.fromCodePoint(0x1F600)+String.fromCodePoint(0x1F44D)+'!';
const EMO2='안녕'+String.fromCodePoint(0x1F600);
console.log('[기본 정제: trim/collapse/tab]');
ok('trim(기본)', (await clean('  hello  ',{})).out==='hello', '');
ok('collapse(기본)', (await clean('a    b',{})).out==='a b', '');
ok('tab(기본)', (await clean('a\tb',{})).out==='a b', '');
ok('줄바꿈은 기본 미적용', (await clean('a\nb',{})).out==='a\nb'||(await clean('a\nb',{})).out.indexOf('\n')>=0, JSON.stringify(await clean('a\\nb',{})));
console.log('[선택 옵션(명시적)]');
ok('줄바꿈 제거', (await clean('a\nb',{removeNewline:true})).out==='a b', '');
ok('제어문자 제거', (await clean(CTRL,{removeControl:true})).out==='ab', JSON.stringify(await clean(CTRL,{removeControl:true})));
ok('보이지 않는 문자 제거', (await clean(INV,{removeInvisible:true})).out==='ab', '');
const allc = await clean('a!@#b$%^&c()',{specialMode:'all'});
ok('모든 특수문자 제거(유지: % ( ) )', allc.out==='ab%c()', JSON.stringify(allc));
ok('특수문자 카운트', allc.ctx.specialRemoved>=6, JSON.stringify(allc.ctx));
ok('기본은 특수문자 유지', (await clean('a!@#b',{})).out==='a!@#b', '');
ok('이모지는 엔진 지원(옵션)', (await clean(EMO,{removeEmoji:true})).out==='안녕!', JSON.stringify(await clean(EMO,{removeEmoji:true})));
const cell = (v,opts,isNum)=>page.evaluate(({v,opts,isNum})=>{ const D=window.__anomaly.DataCleaner; const o=Object.assign({},D.DEFAULTS,opts||{}); const ctx=D.makeContext(); const r=D.cleanCellValue(v,o,isNum,ctx); return {r, ctx, type: r===null?'null':typeof r}; },{v,opts,isNum});
console.log('[셀 단위]');
let c1=await cell('-',{dashToZero:true},true); ok('dash->0 num', c1.r===0 && c1.type==='number', JSON.stringify(c1));
let c2=await cell('-',{dashToZero:true},false); ok('dash kept text', c2.r==='-', JSON.stringify(c2));
let c3=await cell('코드-123',{dashToZero:true},true); ok('code dash', c3.r==='코드-123', JSON.stringify(c3));
let c4=await cell('',{emptyToNull:true},false); ok('empty->null', c4.r===null, JSON.stringify(c4));
let c5=await cell(null,{nullToEmpty:true},false); ok('null->empty', c5.r==='', JSON.stringify(c5));
let c6=await cell(42,{},true); ok('number preserved', c6.r===42 && c6.type==='number', JSON.stringify(c6));
console.log('[테이블 정제 + 요약]');
const tbl = await page.evaluate(()=>{ const D=window.__anomaly.DataCleaner; const cols=['이름 ','금액!','비고']; const rows=[['  홍길동 ','-','일반'],['김철수','1000','ab']]; return D.cleanTable(cols, rows, {dashToZero:true, cleanColSpace:true, cleanColSpecial:true}); });
ok('컬럼명 정리(명시 시)', tbl.columns[0]==='이름' && tbl.columns[1]==='금액', JSON.stringify(tbl.columns));
ok('컬럼명 카운트', tbl.summary.columnsCleaned>=2, JSON.stringify(tbl.summary));
ok('값 trim(기본)', tbl.rows[0][0]==='홍길동', JSON.stringify(tbl.rows[0]));
ok('금액 dash->0', tbl.rows[0][1]===0, JSON.stringify(tbl.rows[0]));
const tbl2 = await page.evaluate(()=>{ const D=window.__anomaly.DataCleaner; const cols=['이름 ','금액!']; const rows=[['홍길동','1']]; return D.cleanTable(cols, rows, {}); });
ok('컬럼명 정리 기본 미적용', tbl2.columns[0]==='이름 ' && tbl2.columns[1]==='금액!', JSON.stringify(tbl2.columns));
console.log('\n결과: '+pass+' passed / '+fail+' failed');
console.log('page errors:', errs.length?errs:'none');
await browser.close(); process.exit(fail?1:0);
