import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const browser = await chromium.launch();
const page = await browser.newPage();
const errs=[]; page.on('pageerror',e=>errs.push(e.message));
await page.goto(new URL('../index.html', import.meta.url).href);
let pass=0,fail=0; const ok=(n,c,d)=>{if(c){pass++;console.log('  OK',n);}else{fail++;console.log('  FAIL',n,'|',d);}};
const clean = (str, opts) => page.evaluate(({str,opts})=>{ const D=window.__anomaly.DataCleaner; const o=Object.assign({}, D.DEFAULTS, opts||{}); const ctx=D.makeContext(); return {out:D.cleanString(str,o,ctx), ctx}; },{str,opts});
const CTRL=String.fromCharCode(97,1,98);
const INV='a'+String.fromCharCode(0x200B,0xFEFF)+'b';
const EMO='안녕'+String.fromCodePoint(0x1F600)+String.fromCodePoint(0x1F44D)+'!';
const EMO2='안녕'+String.fromCodePoint(0x1F600);
ok('trim', (await clean('  hello  ',{})).out==='hello', '');
ok('collapse', (await clean('a    b',{})).out==='a b', '');
ok('newline', (await clean('a\nb',{})).out==='a b', '');
ok('tab', (await clean('a\tb',{})).out==='a b', '');
ok('html', (await clean('<b>강조</b>텍스트',{})).out==='강조텍스트', '');
ok('control', (await clean(CTRL,{})).out==='ab', JSON.stringify(await clean(CTRL,{})));
ok('invisible', (await clean(INV,{})).out==='ab', '');
const cm = await clean('a!@#b$%^&c()',{});
ok('common special', cm.out==='ab%c()', JSON.stringify(cm));
ok('special count', cm.ctx.specialRemoved>=6, JSON.stringify(cm.ctx));
ok('keep mode', (await clean('a!@#b',{specialMode:'keep'})).out==='a!@#b', '');
const all = await clean('가A1-_/().%+ ,;:!@',{specialMode:'all'});
ok('all mode', all.out==='가A1-_/().%+', JSON.stringify(all));
ok('emoji remove', (await clean(EMO,{removeEmoji:true})).out==='안녕', JSON.stringify(await clean(EMO,{removeEmoji:true})));
ok('emoji keep', (await clean(EMO2,{specialMode:'keep'})).out===EMO2, '');
const cell = (v,opts,isNum)=>page.evaluate(({v,opts,isNum})=>{ const D=window.__anomaly.DataCleaner; const o=Object.assign({},D.DEFAULTS,opts||{}); const ctx=D.makeContext(); const r=D.cleanCellValue(v,o,isNum,ctx); return {r, ctx, type: r===null?'null':typeof r}; },{v,opts,isNum});
let c1=await cell('-',{dashToZero:true},true); ok('dash->0 num', c1.r===0 && c1.type==='number', JSON.stringify(c1));
let c2=await cell('-',{dashToZero:true},false); ok('dash kept text', c2.r==='-', JSON.stringify(c2));
let c3=await cell('코드-123',{dashToZero:true},true); ok('code dash', c3.r==='코드-123', JSON.stringify(c3));
let c4=await cell('',{emptyToNull:true},false); ok('empty->null', c4.r===null, JSON.stringify(c4));
let c5=await cell(null,{nullToEmpty:true},false); ok('null->empty', c5.r==='', JSON.stringify(c5));
let c6=await cell(42,{},true); ok('number preserved', c6.r===42 && c6.type==='number', JSON.stringify(c6));
const tbl = await page.evaluate(()=>{ const D=window.__anomaly.DataCleaner; const cols=['이름 ','금액!','비고']; const rows=[['  홍길동 ','-','<b>메모</b>'],['김철수','1000','ab']]; return D.cleanTable(cols, rows, {dashToZero:true}); });
ok('colname clean', tbl.columns[0]==='이름' && tbl.columns[1]==='금액', JSON.stringify(tbl.columns));
ok('colname count', tbl.summary.columnsCleaned>=2, JSON.stringify(tbl.summary));
ok('amount dash->0', tbl.rows[0][1]===0, JSON.stringify(tbl.rows[0]));
ok('html cell', tbl.rows[0][2]==='메모', JSON.stringify(tbl.rows[0]));
console.log('\n결과: '+pass+' passed / '+fail+' failed');
console.log('page errors:', errs.length?errs:'none');
await browser.close(); process.exit(fail?1:0);
