import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { readFileSync } from 'node:fs';
const FX=new URL('./fixtures/', import.meta.url).pathname;
const b64=p=>readFileSync(FX+p).toString('base64');
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1200,height:900}});
const errs=[];page.on('pageerror',e=>errs.push(e.message));page.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
let dl=null;page.on('download',async d=>{dl=await d.path();});
await page.goto(new URL('../index.html', import.meta.url).href);
let pass=0,fail=0;const ok=(n,c,d)=>{if(c){pass++;console.log('  OK',n);}else{fail++;console.log('  FAIL',n,'|',d);}};
await page.click('#railClean');
const styleEq=await page.evaluate(()=>{const a=getComputedStyle(document.getElementById('cleanStatus'));const b=getComputedStyle(document.getElementById('cmpStatus'));return {ta:a.textAlign===b.textAlign, col:a.color===b.color, fs:a.fontSize===b.fontSize, ta_v:a.textAlign, col_v:a.color};});
ok('cleanStatus 정렬=cmpStatus', styleEq.ta && styleEq.ta_v==='center', JSON.stringify(styleEq));
ok('cleanStatus 색상=cmpStatus', styleEq.col, JSON.stringify(styleEq));
ok('cleanStatus 폰트크기=cmpStatus', styleEq.fs, JSON.stringify(styleEq));
await page.evaluate((x)=>{const bin=atob(x);const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);window.__clean.addFiles([new File([a],'prog.xlsx')]);}, b64('prog.xlsx'));
await page.waitForTimeout(50);
await page.check('input[name=convMode][value=xlsx2xlsx]');
const seen={file:false,sheet:false,row:false};
await page.click('#btnCleanRun');
for(let i=0;i<200;i++){const h=await page.evaluate(()=>document.getElementById('cleanStatus').innerHTML);if(h.includes('파일 :'))seen.file=true;if(h.includes('시트 :'))seen.sheet=true;if(h.includes('행 :'))seen.row=true;if(/완료/.test(await page.evaluate(()=>document.getElementById('cleanStatus').textContent)))break;await page.waitForTimeout(20);}
await page.waitForFunction(()=>/완료/.test(document.getElementById('cleanStatus').textContent),{timeout:20000});
ok('진행 중 파일 표시', seen.file, JSON.stringify(seen));
ok('진행 중 시트 표시', seen.sheet, JSON.stringify(seen));
ok('진행 중 행 수 표시', seen.row, JSON.stringify(seen));
ok('완료 후 성공 표시', /완료.*성공/.test(await page.textContent('#cleanStatus')), await page.textContent('#cleanStatus'));
await page.evaluate((x)=>{const bin=atob(x);const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);window.__clean.addFiles([new File([a],'prog2.xlsx'),new File([a],'prog3.xlsx')]);}, b64('prog.xlsx'));
await page.waitForTimeout(50);
await page.click('#btnCleanRun');
await page.waitForTimeout(100);
ok('다중 파일 시 현재 파일 진행바 표시', await page.evaluate(()=>!document.getElementById('cleanFileProgWrap').classList.contains('hidden')), '');
await page.waitForFunction(()=>/완료/.test(document.getElementById('cleanStatus').textContent),{timeout:30000});
ok('진행률 100%', (await page.$eval('#cleanProgress',e=>parseFloat(e.style.width)||0))>=100, '');
console.log('\n결과: '+pass+' passed / '+fail+' failed');
console.log('page errors:', errs.length?errs:'none');
await browser.close();process.exit(fail?1:0);
